version: '3.8' # Or a suitable Docker Compose version
services:
  mongodb:
    image: mongo:latest # Or specify a specific version (e.g., mongo:6.0)
    restart: always # Keep the container running
    ports:
      - 27017:27017 # Map host port to container port
    environment: # Optional: Set environment variables for configuration
      MONGO_INITDB_ROOT_USERNAME: myappadmin
      MONGO_INITDB_ROOT_PASSWORD: myappadmin
